name: FluffyMachines
author: NCBPFluffyBear
description: English maintenance build of FluffyMachines for Slimefun Legacy/Gugu-compatible cores
main: io.ncbpfluffybear.fluffymachines.FluffyMachines

depend: [Slimefun]
softdepend: [mcMMO, NoCheatPlus]

version: ${project.version}
api-version: '26.2'

commands:
  fluffymachines:
    description: FluffyMachines command
    usage: /<command>
    aliases: [fm]
permissions:
  fluffymachines.admin:
    description: Allows use of FluffyMachines administrative commands
